### ISSUE TITLE
instruction expected an executable account

### ISSUE THREAD

**Issue by yin307** [gabrieldemian/minimal-solana-minter#1]
I run anchor test and get error

 can mint an NFT:
     Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: instruction expected an executable account

Thanks !

**Comment by yin307** [comment]
![Screen Shot 2022-03-29 at 15 37 41](https://user-images.githubusercontent.com/18695479/160570026-3e0eadb7-22a4-4935-a3d2-c29435ecf945.png)

**Comment by gabrieldemian** [comment]
hello, @yin307  are you running the test on the devnet? because this error usually happens when you run on the localnet

**Comment by yin307** [comment]
I run in testnet. Let me try in devnet. Thank you so much

Vào 18:46, Th 3, 29 thg 3, 2022 Gabriel ***@***.***> đã viết:

**Comment by gabrieldemian** [comment]
@yin307 is your program working? I just pushed a commit to the code upgrading anchor to a newer version
